-- delete from mozgdolg; --where sorszam=25;
-- select * from mozgdolg;
-- select gravirszam,kiadva from eszkoz where kiadva;
-- select * from kiadotteszkoz;
-- insert into mozgdolg(gravirszam,torzsszam) values('102','93291');
-- insert into mozgktgh(gravirszam,ktghely) values('102','13-321-0');
-- update mozgdolg set meddig=current_timestamp where gravirszam='103';
-- update mozgdolg set meddig=current_timestamp where gravirszam='102';
