insert into me values
('UNI','univerzális'),
('-','határozatlan'),
('%','Százalék'),
('%(t)','Tömegszázalék'),
('%(V)','Térfogatszázalék'),
('%o(t)','Tömegezrelék'),
('%o(V)','Térfogatezrelék'),
('°C','Celsius fok'),
('°F','Fahrenheit'),
('A','Amper'),
('bar','bar'),
('cm','Centiméter'),
('Coll','Inch'),
('F','Farad'),
('Fok','Fok'),
('g','Gramm'),
('h','Óra'),
('hPa','Hektopascal'),
('Hz','Hertz (1/másodperc)'),
('J','Joule'),
('K','Kelvin'),
('kA','Kiloamper'),
('kHz','Kilohertz'),
('kJ','Kilojoule'),
('km','Kilométer'),
('km/h','Kilométer/óra'),
('kN','Kilonewton'),
('kOhm','Kiloohm'),
('kPa','Kilopascal'),
('kt','Kilotonna'),
('kV','Kilovolt'),
('kVA','Kilovoltamper'),
('kW','Kilowatt'),
('kWh','Kilowatt/óra'),
('l','Liter'),
('m','Méter'),
('m/s','Méter/másodperc'),
('m/s2','Méter/másodperc^2'),
('m2','Négyzetméter'),
('m3','Köbméter'),
('mA','Milliamper'),
('mbar','Millibar'),
('mF','Millifarad'),
('mg','Milligramm'),
('MGW','Megawatt'),
('MHz','Megahertz'),
('min','Perc'),
('MJ','Megajoule'),
('mJ','Millijoule'),
('ml','Milliliter'),
('mm','Milliméter'),
('mm2','Négyzetmilliméter'),
('mm3','Köbmilliméter'),
('MN','Meganewton'),
('MOhm','Megaohm'),
('MPa','Megapascal'),
('ms','Millimásodperc'),
('mT','Millitesla'),
('MV','Megavolt'),
('mV','Millivolt'),
('MVA','Megavoltamper'),
('mW','Milliwatt'),
('MWh','Megawattóra'),
('N','Newton'),
('N/m','Newton/Méter'),
('N/mm2','Newton/négyzetmilliméter'),
('nA','Nanoamper'),
('nF','Nanofarad'),
('nm','Nanométer'),
('ns','Nanomásodperc'),
('Ohm','Ohm'),
('Óra','Óra'),
('Pa','Pascal'),
('pF','Pikofarad'),
('ppb','Parts per billion'),
('ppb(m)','Massen-parts per billion'),
('ppb(V)','Volumen-parts per billion'),
('ppm','Parts per million'),
('ppm(m)','Massen-parts per million'),
('ppm(V)','Volumen-parts per million'),
('ppt','Parts per trillion'),
('ppt(m)','Massen-parts per trillion'),
('ppt(V)','Volumen-parts per trillion'),
('ps','Pikomásodperc'),
('s','Másodperc'),
('T','Tesla'),
('t','Tonna'),
('uA','Mikroamper'),
('uF','Mikrofarad'),
('um','Mikrométer'),
('V','Volt'),
('VA','Voltamper'),
('W','Watt');
